name: Rector

permissions:
  contents: read

on:
  pull_request:

jobs:
  rector:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP and Composer
        uses: ./.github/actions/setup-php-composer

      - run: mkdir -p /tmp/rector

      - name: Cache Rector tmp dir
        uses: actions/cache@v4
        with:
          path: /tmp/rector
          key: ${{ runner.os }}-rector-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-rector-

      - name: Run modern refactoring code checks
        run: vendor/bin/rector --dry-run
